## Assignment 1
### Manav Jain
### 20BCE1404

### 1. Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.

In [1]:
name = "Manav Jain"
age = 20

In [2]:
print("My name is", name)
print("My age is", age, "years")

My name is Manav Jain
My age is 20 years


### 2. X="Datascience is used to extract meaningful insights." Split the string

In [42]:
X = "Datascience is used to extract meaningful insights"
Y = X.split()

In [43]:
Y

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights']

### 3. Make a function that gives multiplication of two numbers

In [44]:
def multiply(a, b):
    return a*b

In [45]:
c = 2
d = 3
result = multiply(c,d)
print("Multiplication of", c, "and", d, "is", result)

Multiplication of 2 and 3 is 6


### 4. Create a Dictionary of 5 States with their capitals. also print the keys and values.

In [46]:
state_dict = {"Gujarat": "Gandhinagar", 
             "Madhya Pradesh": "Bhopal", 
             "Punjab": "Chandigarh", 
             "Tamil Nadu": "Chennai",
             "Maharashtra": "Mumbai"}

In [47]:
print("States: ",state_dict.items())

States:  dict_items([('Gujarat', 'Gandhinagar'), ('Madhya Pradesh', 'Bhopal'), ('Punjab', 'Chandigarh'), ('Tamil Nadu', 'Chennai'), ('Maharashtra', 'Mumbai')])


In [48]:
print("Capitals: ",state_dict.values())

Capitals:  dict_values(['Gandhinagar', 'Bhopal', 'Chandigarh', 'Chennai', 'Mumbai'])


### 5. Create a list of 1000 numbers using range function.

In [20]:
range_list = [range(1,1000,1)]

In [49]:
range_list

[range(1, 1000)]

### 6. Create an identity matrix of dimension 4 by 4

In [50]:
import numpy as np

In [51]:
ide_mat = np.identity(4, dtype = int)
print("4-D identity matrix: \n", ide_mat)

4-D identity matrix: 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


### 7. Create a 3x3 matrix with values ranging from 1 to 9

In [52]:
range_mat = np.arange(1, 10).reshape(3,3)

In [53]:
print("3-D range matrix: \n", range_mat)

3-D range matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### 8. Create 2 similar dimensional array and perform sum on them.

In [54]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

In [55]:
arr3 = arr1 + arr2
print("Sum of array 1 and 2: ", arr3)

Sum of array 1 and 2:  [ 6  8 10 12]


### 9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)

In [56]:
import pandas as pd
from datetime import datetime

In [57]:
start_date = datetime.strptime("1-02-2023", "%d-%m-%Y")
end_date = datetime.strptime("1-03-2023", "%d-%m-%Y")

D = 'D'

date_list = pd.date_range(start_date, end_date, freq=D)

In [58]:
date_list

DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01'],
              dtype='datetime64[ns]', freq='D')

### 10. Given a dictionary, convert it into corresponding dataframe and display it dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}

In [59]:
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
dataframe = pd.DataFrame.from_dict(dictionary)

In [60]:
dataframe

Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240